### ISSUE TITLE
Async plot clear

### ISSUE THREAD

**Issue by Zailer43** [Zailer43/PlotCubic#10]
Async the `/plot clear` task so as not to affect server performance

**Comment by Zailer43** [comment]
When I try to make the plot clear asynchronous and fill the plot with blocks that change block state, such as copper, it can cause a crash, I don't know how to do it

```java
Thread: Server Watchdog
Stacktrace:
	at java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	at java.base@17.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
	at java.base@17.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1047)
	at java.base@17.0.1/java.util.concurrent.Semaphore.acquire(Semaphore.java:318)
	at net.minecraft.util.thread.LockHelper.lock(LockHelper.java:48)
	at net.minecraft.world.chunk.PalettedContainer.lock(PalettedContainer.java:44)
	at net.minecraft.world.chunk.PalettedContainer.serialize(PalettedContainer.java:233)
	at net.minecraft.world.chunk.PalettedContainer.method_38302(PalettedContainer.java:67)
	at net.minecraft.world.chunk.PalettedContainer$$Lambda$5355/0x000000080197e6a0.apply(Unknown Source)
	at com.mojang.serialization.Encoder$1.encode(Encoder.java:25)
	at com.mojang.serialization.Codec$2.encode(Codec.java:76)
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14)
	at net.minecraft.world.ChunkSerializer.serialize(ChunkSerializer.java:321)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.save(ThreadedAnvilChunkStorage.java:843)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.save(ThreadedAnvilChunkStorage.java:807)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.unloadChunks(ThreadedAnvilChunkStorage.java:532)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.tick(ThreadedAnvilChunkStorage.java:487)
	at net.minecraft.server.world.ServerChunkManager.tick(ServerChunkManager.java:326)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:319)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:875)
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer.java:289)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
```
